### ISSUE TITLE
uninitialized constant ActiveSupport::Dependencies::Mutex

### ISSUE THREAD

**Issue by tastycode** [radiant/radiant#230]
# radiant test

/usr/lib/ruby/gems/1.8/gems/radiant-0.9.1/vendor/rails/activesupport/lib/active_support/dependencies.rb:55: uninitialized constant ActiveSupport::Dependencies::Mutex (NameError)
        from /usr/local/lib/site_ruby/1.8/rubygems/custom_require.rb:36:in `gem_original_require'
        from /usr/local/lib/site_ruby/1.8/rubygems/custom_require.rb:36:in`require'
        from /usr/lib/ruby/gems/1.8/gems/radiant-0.9.1/vendor/rails/activesupport/lib/active_support.rb:57
        from /usr/local/lib/site_ruby/1.8/rubygems/custom_require.rb:36:in `gem_original_require'
        from /usr/local/lib/site_ruby/1.8/rubygems/custom_require.rb:36:in`require'
        from /usr/lib/ruby/gems/1.8/gems/radiant-0.9.1/vendor/rails/railties/lib/rails_generator.rb:31
        from /usr/local/lib/site_ruby/1.8/rubygems/custom_require.rb:36:in `gem_original_require'
        from /usr/local/lib/site_ruby/1.8/rubygems/custom_require.rb:36:in`require'
        from /usr/lib/ruby/gems/1.8/gems/radiant-0.9.1/bin/radiant:18
        from /usr/bin/radiant:19:in `load'
        from /usr/bin/radiant:19
root@li337-10:/var/www# gem list --local

**\* LOCAL GEMS ***

actionmailer (2.3.11)
actionpack (2.3.11)
activerecord (2.3.11)
activeresource (2.3.11)
activesupport (2.3.11)
mysql (2.8.1)
rack (1.1.2)
radiant (0.9.1)
rails (2.3.11)
rake (0.9.2)
RedCloth (4.2.7)
will_paginate (2.3.15)

root@li337-10:/var/www# ruby -v
ruby 1.8.7 (2010-08-16 patchlevel 302) [i686-linux]

**Comment by wellington1993** [comment]
Thanks @tastycode!
