### ISSUE TITLE
Rails3 support for 1.1.x

### ISSUE THREAD

**Issue by janraasch** [radiant/radiant#391]
Hi guys,

is there/will there ever be a working `v1.1.x` release running on `rails3`? I think this would be much appreciated due to the lack of security patches for `rails2`.

**Comment by saturnflyer** [comment]
@janraasch your contributions would be much appreciated as well.

The master branch is moving in that direction but in needs work. Can you help?

**Comment by Paladin** [comment]
I’ll echo Jim’s sentiments. I started getting the tests to pass, but suddenly life intervened and I haven’t had much time to make more progress. While it’s only temporary and I intend to get back to it in a week or two, we’ll be happy yo have all the help we can get.

The current plan was to get the tests passing for 3.2.x while doing some refactoring to switch it from an app that uses Rails to being an engine that Rails uses, with getting it running “as is" on the latest of the 3.2 branch being the first step. We’ve made some progress towards that, but there’s still a way to go.

**Comment by troystarwalt** [comment]
Jumping in here real quick. I have just installed Radiant, but I noticed it was using Rails 2.3.18. Is that correct or did I miss something? Thanks for all of your hard work!

**Comment by janraasch** [comment]
I'll close this, since there has not been any action in over 3 years 😁 👋🏻
