### ISSUE TITLE
Rails 5 Support

### ISSUE THREAD

**Issue by JorgeDDW** [radiant/radiant#405]
Hi there guys, 

I Want to know how is the support of Radiant and Rails 5.
Any recommendations?

**Comment by jlong** [comment]
Hey Jorge, at this point I don't know of any plans to support Rails 5, although a pull-request would be welcome.

**Comment by protoror** [comment]
i many years use this beautiful cms, but i think project dead, soo sad. i found new cms similar radiant - https://github.com/webgradus/kms
