### ISSUE TITLE
Home Page blank after site migration (v0.9.1)

### ISSUE THREAD

**Issue by serverok** [radiant/radiant#417]
I am moving a very old version of raidant CMS v0.9.1 to a new server.

I installed same version of ruby/rails/gem on new server. When i go to home page of CMS, it shows blank page, sub pages works fine.

For some reason home page is not getting to show_page function.

here is code from config/routes.rb

```
  # Site URLs
  map.with_options(:controller => 'site') do |site|
    site.root                                                    :action => 'show_page', :url => '/'
    site.not_found         'error/404',                          :action => 'not_found'
    site.error             'error/500',                          :action => 'error'

    # Everything else
    site.connect           '*url',                               :action => 'show_page'
  end
```

Any idea how to fix this problem ?

**Comment by avonderluft** [comment]
I suspect this may be due to the ruby version on the new server.   Radiant became compatible with ruby 1.9.3 with v1.0.1.  Prior to this, you would need ruby 1.8.x

**Comment by serverok** [comment]
I am using Ruby 1.8.7, that work file on source server.  Installing all  gems same version as in LIVE version. Only problem is for  home page, everything else works. 

Anyway i can find our what controller#action this / page goes ?

@saturnflyer

**Comment by jomz** [comment]
Your production.log should tell you which controller handled the request for "/".

I can't quite remember ever running into this issue myself.. my hunch is there's something wrong with the layout? Some radius doing a conditional with the domain name perhaps?

By blank, you mean there's zero html being sent?

Maybe update a page to clear the cache, perhaps you solved the issue but are seeing a cached version of the home page?

**Comment by serverok** [comment]
Thanks @jomz for the reply.

@avonderluft helped me to fix the problem. There was an index.html file in public folder, that caused the request not reach the application.
